### ISSUE TITLE
Graceful green timeout results in a 500 rather than a 504

### ISSUE THREAD

**Issue by mostlyAtNight** [MerginMaps/server#338]
I noticed in this request that was aborted due to the timout being reached, that it resulted in a 500 instead of the expected 504 - perhaps due to the unexpected database exception:

```
2024-11-30 03:16:47	
[ERROR] [220563] HTTP 500: (path=/v1/project/push/finish/fe910406-48f5-4328-8eec-c73c7e397ed8|hash=8f7fa981|version=2024.7.1): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mergin/sync/public_api_controller.py", line 1072, in push_finish
  pv = ProjectVersion(
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
  with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  compat.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
  raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
  return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mergin/sync/models.py", line 792, in __init__
  db.session.flush()
  File "<string>", line 2, in flush
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 3449, in flush
  self._flush(objects)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 3588, in _flush
  with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  compat.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
  raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 3549, in _flush
  flush_context.execute()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
  rec.execute(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
  util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
  _emit_insert_statements(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
  result = connection._execute_20(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
  return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
  return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
  ret = self._execute_context(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
  self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
  util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
  raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
  self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
  cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/psycogreen/gevent.py", line 36, in gevent_wait_callback
  wait_read(conn.fileno(), timeout=timeout)
  File "src/gevent/_hub_primitives.py", line 353, in gevent._gevent_c_hub_primitives.wait_read
  File "src/gevent/_hub_primitives.py", line 367, in gevent._gevent_c_hub_primitives.wait_read
  File "src/gevent/_hub_primitives.py", line 350, in gevent._gevent_c_hub_primitives.wait_on_watcher
  File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  gevent.timeout.Timeout: 30 seconds
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
  rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
  return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/decorator.py", line 68, in wrapper
  response = function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
  response = function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/validation.py", line 399, in wrapper
  return function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/response.py", line 112, in wrapper
  response = function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/parameter.py", line 120, in wrapper
  return function(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mergin/auth/app.py", line 69, in wrapped_func
  return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mergin/sync/public_api_controller.py", line 680, in wrapper
  return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mergin/sync/public_api_controller.py", line 1098, in push_finish
  upload.clear()
  File "/usr/local/lib/python3.10/dist-packages/mergin/sync/models.py", line 1065, in clear
  move_to_tmp(self.upload_dir, self.id)
  File "/usr/local/lib/python3.10/dist-packages/mergin/sync/models.py", line 1048, in upload_dir
  return os.path.join(self.project.storage.project_dir, "tmp", self.id)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
  return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/attributes.py", line 959, in get
  value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/attributes.py", line 995, in _fire_loader_callables
  return self.callable_(state, passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/strategies.py", line 872, in _load_for_state
  primary_key_identity = self._get_ident_for_use_get(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/strategies.py", line 931, in _get_ident_for_use_get
  return [
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/strategies.py", line 932, in <listcomp>
    get_attr(state, dict_, self._equated_columns[pk], passive=passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/mapper.py", line 3018, in _get_state_attr_by_column
    return state.manager[prop.key].impl.get(state, dict_, passive=passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/attributes.py", line 959, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/attributes.py", line 990, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/state.py", line 712, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 1451, in load_scalar_attributes
    result = load_on_ident(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 407, in load_on_ident
    return load_on_pk_identity(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 724, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
    raise sa_exc.PendingRollbackError(

sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 30 seconds (Background on this error at: https://sqlalche.me/e/14/7s2a)
```

**Comment by MarcelGeo** [comment]
I found section about catching timeout in docs

https://www.gevent.org/api/gevent.timeout.html
